 const nsfwmenu = (prefix) => {
    return `
  ❏ Nsfw menu
  | ● *${prefix}neko*
  | ● *${prefix}waifu*
  | ● *${prefix}chiisaihentai*
  | ● *${prefix}trap*
  | ● *${prefix}blowjob*
  | ● *${prefix}nsfwneko*
  | ● *${prefix}yaoi*
  | ● *${prefix}ecchi*
  | ● *${prefix}hentai*
  | ● *${prefix}loli*
  | ● *${prefix}ahegao*
  | ● *${prefix}hololewd*
  | ● *${prefix}sideoppai*
  | ● *${prefix}animefeets*
  | ● *${prefix}animebooty*
  | ● *${prefix}animethighss*
  | ● *${prefix}hentaiparadise*
  | ● *${prefix}animearmpits*
  | ● *${prefix}hentaifemdom*
  | ● *${prefix}lewdanimegirls*
  | ● *${prefix}biganimetiddies*
  | ● *${prefix}animebellybutton*
  | ● *${prefix}hentai4everyone*
  | ● *${prefix}bj*
  | ● *${prefix}ero*
  | ● *${prefix}cum*
  | ● *${prefix}feet*
  | ● *${prefix}yuri*
  | ● *${prefix}ngif*
  | ● *${prefix}lewd*
  | ● *${prefix}feed*
  | ● *${prefix}eron*
  | ● *${prefix}solo*
  | ● *${prefix}gasm*
  | ● *${prefix}poke*
  | ● *${prefix}anal*
  | ● *${prefix}holo*
  | ● *${prefix}tits*
  | ● *${prefix}kuni*
  | ● *${prefix}erok*
  | ● *${prefix}smug*
  | ● *${prefix}baka*
  | ● *${prefix}solog*
  | ● *${prefix}feetg*
  | ● *${prefix}lewdk*
  | ● *${prefix}cuddle*
  | ● *${prefix}eroyuri*
  | ● *${prefix}cum_jpg*
  | ● *${prefix}erofeet*
  | ● *${prefix}holoero*
  | ● *${prefix}classic*
  | ● *${prefix}erokemo*
  | ● *${prefix}fox_girl*
  | ● *${prefix}futanari*
  | ● *${prefix}lewdkemo*
  | ● *${prefix}pussy_jpg*
  | ● *${prefix}kemonomimi*
  | ● *${prefix}nsfw_avatar*
  | ● *${prefix}nsfw_neko_gif*
  | ● *${prefix}random_hentai_gif*`
}
exports.nsfwmenu = nsfwmenu